services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: vikunja
      POSTGRES_PASSWORD: vikunja
      POSTGRES_DB: vikunja
    volumes:
      - ./db:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      VIKUNJA_DATABASE_TYPE: postgres
      VIKUNJA_DATABASE_HOST: db
      VIKUNJA_DATABASE_USER: vikunja
      VIKUNJA_DATABASE_PASSWORD: vikunja
      VIKUNJA_DATABASE_DATABASE: vikunja
      VIKUNJA_SERVICE_PUBLICURL: http://localhost:3456
      VIKUNJA_CORS_ENABLE: false
    ports:
      - "3456:3456"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    environment:
      VIKUNJA_CORS_ENABLE: false
    ports:
      - "8081:80"
    depends_on:
      - api
